
services:
  mongo:
    image: mongo:7.0
    container_name: mongodb_local
    
    ports:
      - "27017:27017"
    
    environment:
      MONGO_INITDB_DATABASE: miBaseDeDatos
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ejemplo123
    
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    
    container_name: servidor_node
    
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://root:ejemplo123@mongo:27017/miBaseDeDatos?authSource=admin"
    depends_on:
      - mongo

volumes:
  mongo_data:
